apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: http-proxy-guestbook-server
  namespace: guestbook
spec:
  virtualhost:
    fqdn: server.guestbook.wjmcloud.top
#    tls:
#     secretName: wjmcloud-top-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: guestbook-ui
          port: 80
